# Directory where virus definitions will be stored
DatabaseDirectory "C:\Users\CompuTop\Downloads\the-full-project-main - 2\the-full-project-main\clamav\database"

# Log file for freshclam
UpdateLogFile "C:\Users\CompuTop\Downloads\the-full-project-main - 2\the-full-project-main\clamav\freshclam.log"

# Official ClamAV mirror
DatabaseMirror database.clamav.net

# Uncomment to disable SSL (helps with Windows builds)
# DNSDatabaseInfo current.cvd.clamav.net

# Allow usage without running as a service
Foreground yes

# Number of attempts per mirror
MaxAttempts 3
